apiVersion: v1
kind: Service
metadata:
  name: toolkit-api
  labels:
    app: toolkit
    component: api
spec:
  selector:
    app: toolkit
    component: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
